### ISSUE TITLE
Enter, tab, backspace don't work

### ISSUE THREAD

**Issue by KingDuckZ** [GWuk/PwdHash2#4]
As per the title, pressing enter doesn't submit the password, instead it adds an extra character to the password field which can't be corrected by pressing backspace either (it would also add one more character).

**To Reproduce**
1. Go to a password field
2. Press F2
3. Type some text and press enter
4. Password doesn't get submitted

**Expected behavior**
As it was the case with the original pwdhash plugin, I'd expect enter to submit the form, backspace to delete the last character and tab to move the focus to the next widget.

**Browser (please complete the following information):**
 - Firefox Version 60.8.0esr 64-bit (stable firefox on gentoo)
 - PwdHash2 Version 1.0

**Comment by GWuk** [comment]
I can reproduce this with only with the enter key, but not with tab and backspace:

- tab moves the focus to the next widget, performing the password hash (ok)
- backspace deletes as expected (ok)
- enter adds character (bug, I'll fix that)

Can you give me an example URL where tab and backspace do not work? Maybe there is some JS from the site interfering.
