### ISSUE TITLE
Restrict/require special characters

### ISSUE THREAD

**Issue by psturm-de** [GWuk/PwdHash2#6]
I ran into the fact that some sites deny some special characters.
So - however - PayPal doesn't allow '+' in my password as generated for this site.

On the other hand some sites require at least one digit and/or special character. So they're may included depending on hashing input but not guaranteed.

I have no idea how to implement this because a site specific list of allowed or required characters would be against the concept of the add-on.

EDIT: PayPal currently allows letters, numbers and these characters: !@#$%^&*()

**Comment by GWuk** [comment]
Yes, specific special characters are a problem.

If you need digits or special characters for a site, using one of their kind in your master password makes PwdHash consider this class of characters in the site password. So your second request can be satisfied (kind of).

But making PwdHash exclude some characters from the site password, that's not possible in a generic way.

You could try a different master password, with high probability it will not include the same special character as another one. But that's of course not guaranteed.

As you stated correctly, other solutions I can think of violate the concept.

So having more than one master password provides a workaround for this issue.
